# Gets all logged in user's posts. Should send a valid Access Token through headers (obtained through /login or /refresh-token)
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1YW4iLCJwYXNzd29yZCI6IiQyYiQxMCRYU0tIWW9RN05pUWpMZ1gzTy5FbGJPNWtRdWNxaEtCYmgweERwRWE0RWVtTERwUmdDWnFMLiIsImNyZWF0aW9uVGltZXN0YW1wIjoxNjQ5OTQyNTIxOTg1LCJpYXQiOjE2NDk5NDI1MjEsImV4cCI6MTY0OTk0MjUzMX0.JF1hORODscXXyiV8MBNegIvugEffQoNY1wAac1JcNr0

###


# Creates a new user (just for test purposes)
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Juan",
    "password": "1234"
}

###

# On successful login, generates and responds with both new authToken and refreshToken (Empty userDB on begining)
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Juan",
    "password": "1234"
}