GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1YW4iLCJwYXNzd29yZCI6IiQyYiQxMCQua25tMnp0Nm8uVkJhb1d1LzAvZkp1OHhCa283cENkSE12NURWSzV1THRyeHgvY2I1elRWdSIsImNyZWF0aW9uVGltZXN0YW1wIjoxNjQ5ODcxMzIwNDE0LCJpYXQiOjE2NDk4NzEzMjB9.sP-602LOvhjhsnG0xIm2y6F2yA7MOZjIBxXfizSEAn0

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Juan",
    "password": "1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Juan",
    "password": "1234"
}